---
- hosts: app-servers
  tasks:
    - name: "Check if APACHE is installed"
      package_facts:
        manager: "auto"
    - name: "Apache result"
      debug:
        msg: "Apache found"
      when: "'apache2' in ansible_facts.packages"
    - name: "Apache result"
      debug:
        msg: "Apache NOT found"
      when: "'apache2' not in ansible_facts.packages"
