---
- hosts: app-servers
  tasks:
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 172.16.25.10:/data/nfs
        path: /mnt/shared_data
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
