---
# Pre-requisites, install and update packages
- import_playbook: all/main.yml

# Add apache on servers
- import_playbook: app-server/main.yml

# Add MySQL to servers
- import_playbook: db-server/main.yml

# HAProxy install, NFS servers
- import_playbook: masters/main.yml

# Configure HAProxy for MySQL - DO NOT RUN, it will remove MySQL replication
#- import_playbook: db-master/main.yml

# Configure HAProxy for Apache
- import_playbook: app-master/main.yml
