---
# Pre-requisites, install and update packages
- import_playbook: all/main.yml

# Add apache on servers
- import_playbook: app-server/main.yml

# Add MySQL to servers
- import_playbook: db-server/main.yml

# HAProxy install, TLS termination, NFS servers
- import_playbook: masters/main.yml

# Configure HAProxy for MySQL
- import_playbook: db-master/main.yml

# Configure HAProxy for Apache
- import_playbook: app-master/main.yml
